// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKU3AJWDh5SHSyF6BRgs26wplHejAm2y0',
    appId: '1:183947127883:web:ba81717101aae9b505b1ce',
    messagingSenderId: '183947127883',
    projectId: 'messagingapp-45514',
    authDomain: 'messagingapp-45514.firebaseapp.com',
    storageBucket: 'messagingapp-45514.appspot.com',
    measurementId: 'G-Z0BR6EMDZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyx_rvCQHNuBM0TLyvgS_A0Yu3vguCBJk',
    appId: '1:183947127883:android:7e60ae53968539eb05b1ce',
    messagingSenderId: '183947127883',
    projectId: 'messagingapp-45514',
    storageBucket: 'messagingapp-45514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxk346cGKxGqQRQDBES6Az9UBwR8tU_A',
    appId: '1:183947127883:ios:edbf2bfa08a6282005b1ce',
    messagingSenderId: '183947127883',
    projectId: 'messagingapp-45514',
    storageBucket: 'messagingapp-45514.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxk346cGKxGqQRQDBES6Az9UBwR8tU_A',
    appId: '1:183947127883:ios:edbf2bfa08a6282005b1ce',
    messagingSenderId: '183947127883',
    projectId: 'messagingapp-45514',
    storageBucket: 'messagingapp-45514.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKU3AJWDh5SHSyF6BRgs26wplHejAm2y0',
    appId: '1:183947127883:web:529481bc7a736f9805b1ce',
    messagingSenderId: '183947127883',
    projectId: 'messagingapp-45514',
    authDomain: 'messagingapp-45514.firebaseapp.com',
    storageBucket: 'messagingapp-45514.appspot.com',
    measurementId: 'G-K3145BPMTC',
  );
}
