// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS2eNHJ7HkKHBXMawDY_IRS1pTpKVqIcM',
    appId: '1:654230966901:web:ed697aa9e05d9acefe5e3c',
    messagingSenderId: '654230966901',
    projectId: 'artfolioapp-95eb3',
    authDomain: 'artfolioapp-95eb3.firebaseapp.com',
    storageBucket: 'artfolioapp-95eb3.appspot.com',
    measurementId: 'G-K5H6WPWRDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3rG8uiatrGPIw-QN1efgKGMIJ3Az1nU4',
    appId: '1:654230966901:android:92320f314d0e30eafe5e3c',
    messagingSenderId: '654230966901',
    projectId: 'artfolioapp-95eb3',
    storageBucket: 'artfolioapp-95eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJ8x4PcH6FkzstLTEUTFCy55ZJTao4YU',
    appId: '1:654230966901:ios:5ba42eead7149f04fe5e3c',
    messagingSenderId: '654230966901',
    projectId: 'artfolioapp-95eb3',
    storageBucket: 'artfolioapp-95eb3.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJ8x4PcH6FkzstLTEUTFCy55ZJTao4YU',
    appId: '1:654230966901:ios:5ba42eead7149f04fe5e3c',
    messagingSenderId: '654230966901',
    projectId: 'artfolioapp-95eb3',
    storageBucket: 'artfolioapp-95eb3.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS2eNHJ7HkKHBXMawDY_IRS1pTpKVqIcM',
    appId: '1:654230966901:web:0d91bcf751c6af05fe5e3c',
    messagingSenderId: '654230966901',
    projectId: 'artfolioapp-95eb3',
    authDomain: 'artfolioapp-95eb3.firebaseapp.com',
    storageBucket: 'artfolioapp-95eb3.appspot.com',
    measurementId: 'G-0B4L9J082X',
  );
}
